apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-http
spec:
  containers:
  - name: liveness
    # https://github.com/kubernetes/kubernetes/blob/master/test/images/agnhost/liveness/server.go
    # This application will return status code 200 for first 10 seconds but after that will return 500.
    # 
    image: registry.k8s.io/e2e-test-images/agnhost:2.40 
    args:
    - liveness
    livenessProbe:
      httpGet: 
        # kubelet will perform probe by sending http get request to container runnning at 8080 port at /healthz path.
        # If path returns status code >= 200 and < 400, probe is successful otherwise, probe will fail.
        # Probe will fail when executed after first 10 sec as containerized application is configured like it.
        path: /healthz
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
