apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: registry.k8s.io/busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600 # liveness probe will fail after 30s as /tmp/healthy will be removed.
    livenessProbe: # To execute liveness probe, kubelet should execute "cat /tmp/healthy"
      exec: # Sucsess if return code of command is 0, otherwise kubelet will kill and restart the container.
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 5 # kubelet should wait 5 sec before executing first liveness probe.
      periodSeconds: 5 # kubelet should execute liveness every 5 seconds
